### ISSUE TITLE
Add cleanup of downloaded setuptools-*.zip files

### ISSUE THREAD

**Issue by tersmitten** [Oefenweb/ansible-pip#3]
http://stackoverflow.com/a/31395118/138779

**Comment by Petrox** [comment]
Lol. build fail, because of the idempotency test: #4 

```
The command "ansible-playbook -i tests/inventory tests/test.yml --connection=local --sudo -vvvv" exited with 0.

5.25s$ ansible-playbook -i tests/inventory tests/test.yml --connection=local --sudo | grep -q 'changed=0.*failed=0' && (echo 'Idempotence test: pass' && exit 0) || (echo 'Idempotence test: fail' && exit 1)

Idempotence test: fail

The command "ansible-playbook -i tests/inventory tests/test.yml --connection=local --sudo | grep -q 'changed=0.*failed=0' && (echo 'Idempotence test: pass' && exit 0) || (echo 'Idempotence test: fail' && exit 1)

" exited with 1.
```

**Comment by tersmitten** [comment]
You are removing the wrong file. See https://bitbucket.org/pypa/setuptools/issues/454/cleanup-of-downloaded-zip-file

**Comment by Petrox** [comment]
Okay,the PR is not even a full solution because of the redownload-recheck->changed problems, so please ignore it.

On the other hand the link states that there should be no zip file ever left behind, so we shouldn't remove anything ever.

If that would be true, my playbooks folder would not look like this:

```
$ ls -l playbooks/
total 672
-rw-rw-r-- 1 petros petros   5420 Nov 19 20:30 localdev.yml
-rw-r--r-- 1 petros petros 670884 Nov 16 02:39 setuptools-18.5.zip
```

(I've skipped the tempfiles left by other ansible roles, I might open an issue for them, but I don't have time for a PR :) )

 Leaving artifacts in the playbook folder breaks all the base concepts of ansible, it does not matter how I tried to remove one. 

 What's the solution?

**Comment by tersmitten** [comment]
Remove `setuptools-*.zip` in the current working directory?

Something like this (not tested):

```
- name: remove setuptools files
  file: src={{ item }} state=absent
  with_lines: ls ./setuptools-*.zip
```
